# Generated by Django 4.2.7 on 2025-08-21 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import poultry.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(default=poultry.core.models.generate_batch_id, editable=False, max_length=20, unique=True)),
                ('batch_name', models.CharField(max_length=255)),
                ('date_acquired', models.DateField()),
                ('initial_count', models.PositiveIntegerField()),
                ('breed', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_acquired'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('disease', models.CharField(blank=True, max_length=255)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('health_status', models.CharField(max_length=255)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='core.flock')),
            ],
        ),
        migrations.CreateModel(
            name='FlockSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('weight_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('weight_3', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('weight_4', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('weight_5', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_feed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_water', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='core.flock')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=255)),
                ('number_of_initial_birds', models.PositiveIntegerField(default=0)),
                ('price_per_initial_bird', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_initial_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('food_expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('water_expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('vaccination_expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('medicine_expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('lab_expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('remaining_birds', models.PositiveIntegerField(default=0)),
                ('selling_price_per_bird', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_records', to='core.flock')),
            ],
        ),
    ]
