# Generated by Django 3.2.25 on 2025-06-02 13:39

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(default=core.models.generate_batch_id, editable=False, max_length=20, unique=True)),
                ('batch_name', models.CharField(max_length=255)),
                ('date_acquired', models.DateField()),
                ('initial_count', models.PositiveIntegerField()),
                ('breed', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_acquired'],
            },
        ),
    ]
