# Generated by Django 3.2.25 on 2025-07-20 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_flock'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlockSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('avg_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_feed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_water', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='core.flock')),
            ],
            options={
                'unique_together': {('flock', 'day')},
            },
        ),
    ]
