# Generated by Django 3.2.25 on 2025-07-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_flocksummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flocksummary',
            name='avg_weight',
        ),
        migrations.AddField(
            model_name='flocksummary',
            name='weight_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='flocksummary',
            name='weight_2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='flocksummary',
            name='weight_3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='flocksummary',
            name='weight_4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='flocksummary',
            name='weight_5',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
