# Generated by Django 3.2.25 on 2025-07-21 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250720_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.PositiveIntegerField()),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('disease', models.CharField(blank=True, max_length=255)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('health_status', models.CharField(max_length=255)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='core.flock')),
            ],
            options={
                'unique_together': {('flock', 'day')},
            },
        ),
    ]
