# Generated by Django 3.2.25 on 2025-07-21 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_healthcheck'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flocksummary',
            unique_together={('flock', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='healthcheck',
            unique_together={('flock', 'date')},
        ),
        migrations.RemoveField(
            model_name='flocksummary',
            name='day',
        ),
        migrations.RemoveField(
            model_name='healthcheck',
            name='day',
        ),
    ]
