# Generated by Django 3.2.25 on 2025-07-23 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250721_0705'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flocksummary',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='healthcheck',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=255)),
                ('number_of_initial_birds', models.PositiveIntegerField()),
                ('price_per_initial_bird', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('water_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vaccination_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medicine_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lab_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_birds', models.PositiveIntegerField()),
                ('selling_price_per_bird', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_records', to='core.flock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
