# Generated by Django 3.2.25 on 2025-07-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250723_0740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financerecord',
            options={},
        ),
        migrations.AddField(
            model_name='financerecord',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='financerecord',
            name='total_initial_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='financerecord',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='food_expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='lab_expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='medicine_expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='number_of_initial_birds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='price_per_initial_bird',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='remaining_birds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='selling_price_per_bird',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='vaccination_expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='water_expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
