# Generated by Django 3.2.25 on 2025-07-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20250723_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financerecord',
            name='total_expenses',
        ),
        migrations.RemoveField(
            model_name='financerecord',
            name='total_revenue',
        ),
    ]
